pub:
  container_name: 'pub'
  build: ./pub
  ports: 
    - "3000:3000"
  links: 
    - redis
redis:
  container_name: 'redis'
  image: redis
  ports: 
    - "6379:6379"
  
sub:
  container_name: 'sub'
  build: ./sub 
  ports: 
    - "4000:4000"
  links: 
    - redis
api:
  container_name: 'api'
  build: ./api
  ports: 
    - "5000:5000"
